name: Load Config Action

description: GitHub Actions to load config.

author: technote-space

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests
    default: ${{ github.token }}
    required: false
  CONFIG_FILENAME:
    description: Config filename
    required: true
  PREFIX:
    description: Prefix
    required: false
  SUFFIX:
    description: Suffix
    required: false
  RELATIVE_PATH:
    description: Relative path
    default: '.github'
    required: false
  REF:
    description: The name of the commit/branch/tag
    default: ${{ github.ref }}
    required: false
  IGNORE_WARNING:
    description: Whether to ignore warning
    required: false

branding:
  icon: 'settings'
  color: 'gray-dark'

runs:
  using: node16
  main: lib/main.js
